[project]
name = "benranderson-github-io"
version = "0.1.0"
description = "Personal website."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ghp-import>=2.1.0",
    "pelican[markdown]>=4.11.0.post0",
]

[dependency-groups]
dev = ["ruff>=0.14.6"]
